apiVersion: v1
kind: Pod
metadata:
  name: logger-test
  namespace: demo
  labels:
    app: logger-test
spec:
  restartPolicy: Never
  containers:
    - name: logger-test
      image: busybox:1.36
      command: ["/bin/sh", "-c"]
      args:
        - |
          while true; do
            echo "hello from gg-logging $(date)";
            sleep 2;
          done
